### ISSUE TITLE
Spring-Mirai-Server-master\Spring-Mirai-Server-master\.mvn\wrapper\maven-wrapper.jar中没有主清单属性

### ISSUE THREAD

**Issue by evepupil** [ProtobufBot/Go-Mirai-Client#10]
Spring-Mirai-Server-master\Spring-Mirai-Server-master\.mvn\wrapper\maven-wrapper.jar中没有主清单属性

**Comment by lz1998** [comment]
是IDEA吗？修改过什么吗？

**Comment by lz1998** [comment]
可以去Spring-Mirai-Server提issue
