### ISSUE TITLE
群发送图片上传失败

### ISSUE THREAD

**Issue by jxygzzy** [ProtobufBot/Go-Mirai-Client#13]
```
ERRO[2021-09-24 21:39:40] failed to upload group image, dial tcp 180.109.192.140:14000: i/o timeout
connect error
github.com/Mrs4s/MiraiGo/client.(*QQClient).highwayUploadByBDH
        github.com/Mrs4s/MiraiGo@v0.0.0-20210906051204-59288fc4dcf2/client/highway.go:121
github.com/Mrs4s/MiraiGo/client.(*QQClient).UploadGroupImage
        github.com/Mrs4s/MiraiGo@v0.0.0-20210906051204-59288fc4dcf2/client/image.go:60
github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.preProcessGroupSendingMessage
        github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/api_handler.go:98
github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.HandleSendGroupMsg
        github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/api_handler.go:173
github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.handleApiFrame
        github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/remote.go:181
github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.OnWsRecvMessage.func1
        github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/remote.go:143
github.com/ProtobufBot/Go-Mirai-Client/pkg/safe_ws.NewSafeWebSocket.func2.1
        github.com/ProtobufBot/Go-Mirai-Client/pkg/safe_ws/safe_ws.go:78
github.com/ProtobufBot/Go-Mirai-Client/pkg/util.SafeGo.func1
        github.com/ProtobufBot/Go-Mirai-Client/pkg/util/util.go:118
runtime.goexit
        runtime/asm_amd64.s:1581
upload failed
github.com/Mrs4s/MiraiGo/client.(*QQClient).UploadGroupImage
        github.com/Mrs4s/MiraiGo@v0.0.0-20210906051204-59288fc4dcf2/client/image.go:63
github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.preProcessGroupSendingMessage
        github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/api_handler.go:98
github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.HandleSendGroupMsg
        github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/api_handler.go:173
github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.handleApiFrame
        github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/remote.go:181
github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.OnWsRecvMessage.func1
        github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/remote.go:143
github.com/ProtobufBot/Go-Mirai-Client/pkg/safe_ws.NewSafeWebSocket.func2.1
        github.com/ProtobufBot/Go-Mirai-Client/pkg/safe_ws/safe_ws.go:78
github.com/ProtobufBot/Go-Mirai-Client/pkg/util.SafeGo.func1
        github.com/ProtobufBot/Go-Mirai-Client/pkg/util/util.go:118
runtime.goexit
        runtime/asm_amd64.s:1581
```
私聊没问题，只会  failed to upload group image

**Comment by lz1998** [comment]
> ```
> ERRO[2021-09-24 21:39:40] failed to upload group image, dial tcp 180.109.192.140:14000: i/o timeout
> connect error
> github.com/Mrs4s/MiraiGo/client.(*QQClient).highwayUploadByBDH
>         github.com/Mrs4s/MiraiGo@v0.0.0-20210906051204-59288fc4dcf2/client/highway.go:121
> github.com/Mrs4s/MiraiGo/client.(*QQClient).UploadGroupImage
>         github.com/Mrs4s/MiraiGo@v0.0.0-20210906051204-59288fc4dcf2/client/image.go:60
> github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.preProcessGroupSendingMessage
>         github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/api_handler.go:98
> github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.HandleSendGroupMsg
>         github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/api_handler.go:173
> github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.handleApiFrame
>         github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/remote.go:181
> github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.OnWsRecvMessage.func1
>         github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/remote.go:143
> github.com/ProtobufBot/Go-Mirai-Client/pkg/safe_ws.NewSafeWebSocket.func2.1
>         github.com/ProtobufBot/Go-Mirai-Client/pkg/safe_ws/safe_ws.go:78
> github.com/ProtobufBot/Go-Mirai-Client/pkg/util.SafeGo.func1
>         github.com/ProtobufBot/Go-Mirai-Client/pkg/util/util.go:118
> runtime.goexit
>         runtime/asm_amd64.s:1581
> upload failed
> github.com/Mrs4s/MiraiGo/client.(*QQClient).UploadGroupImage
>         github.com/Mrs4s/MiraiGo@v0.0.0-20210906051204-59288fc4dcf2/client/image.go:63
> github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.preProcessGroupSendingMessage
>         github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/api_handler.go:98
> github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.HandleSendGroupMsg
>         github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/api_handler.go:173
> github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.handleApiFrame
>         github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/remote.go:181
> github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.OnWsRecvMessage.func1
>         github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/remote.go:143
> github.com/ProtobufBot/Go-Mirai-Client/pkg/safe_ws.NewSafeWebSocket.func2.1
>         github.com/ProtobufBot/Go-Mirai-Client/pkg/safe_ws/safe_ws.go:78
> github.com/ProtobufBot/Go-Mirai-Client/pkg/util.SafeGo.func1
>         github.com/ProtobufBot/Go-Mirai-Client/pkg/util/util.go:118
> runtime.goexit
>         runtime/asm_amd64.s:1581
> ```
> 
> 私聊没问题，只会 failed to upload group image

是阿里云吗？稳定复现吗？

**Comment by jxygzzy** [comment]
> > ```
> > ERRO[2021-09-24 21:39:40] failed to upload group image, dial tcp 180.109.192.140:14000: i/o timeout
> > connect error
> > github.com/Mrs4s/MiraiGo/client.(*QQClient).highwayUploadByBDH
> >         github.com/Mrs4s/MiraiGo@v0.0.0-20210906051204-59288fc4dcf2/client/highway.go:121
> > github.com/Mrs4s/MiraiGo/client.(*QQClient).UploadGroupImage
> >         github.com/Mrs4s/MiraiGo@v0.0.0-20210906051204-59288fc4dcf2/client/image.go:60
> > github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.preProcessGroupSendingMessage
> >         github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/api_handler.go:98
> > github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.HandleSendGroupMsg
> >         github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/api_handler.go:173
> > github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.handleApiFrame
> >         github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/remote.go:181
> > github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.OnWsRecvMessage.func1
> >         github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/remote.go:143
> > github.com/ProtobufBot/Go-Mirai-Client/pkg/safe_ws.NewSafeWebSocket.func2.1
> >         github.com/ProtobufBot/Go-Mirai-Client/pkg/safe_ws/safe_ws.go:78
> > github.com/ProtobufBot/Go-Mirai-Client/pkg/util.SafeGo.func1
> >         github.com/ProtobufBot/Go-Mirai-Client/pkg/util/util.go:118
> > runtime.goexit
> >         runtime/asm_amd64.s:1581
> > upload failed
> > github.com/Mrs4s/MiraiGo/client.(*QQClient).UploadGroupImage
> >         github.com/Mrs4s/MiraiGo@v0.0.0-20210906051204-59288fc4dcf2/client/image.go:63
> > github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.preProcessGroupSendingMessage
> >         github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/api_handler.go:98
> > github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.HandleSendGroupMsg
> >         github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/api_handler.go:173
> > github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.handleApiFrame
> >         github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/remote.go:181
> > github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.OnWsRecvMessage.func1
> >         github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/remote.go:143
> > github.com/ProtobufBot/Go-Mirai-Client/pkg/safe_ws.NewSafeWebSocket.func2.1
> >         github.com/ProtobufBot/Go-Mirai-Client/pkg/safe_ws/safe_ws.go:78
> > github.com/ProtobufBot/Go-Mirai-Client/pkg/util.SafeGo.func1
> >         github.com/ProtobufBot/Go-Mirai-Client/pkg/util/util.go:118
> > runtime.goexit
> >         runtime/asm_amd64.s:1581
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 私聊没问题，最后上传群图失败
> 
> 是阿里云吗？稳定复现吗？

腾讯云、稳定复现

**Comment by ttlvip** [comment]
一样， 腾讯云 稳定复现

**Comment by lz1998** [comment]
> 一样， 腾讯云 稳定复现

我这边暂时没办法复现，猜测可能是网络原因

**Comment by ttlvip** [comment]
> ```
> ERRO[2021-09-24 21:39:40] failed to upload group image, dial tcp 180.109.192.140:14000: i/o timeout
> connect error
> github.com/Mrs4s/MiraiGo/client.(*QQClient).highwayUploadByBDH
>         github.com/Mrs4s/MiraiGo@v0.0.0-20210906051204-59288fc4dcf2/client/highway.go:121
> github.com/Mrs4s/MiraiGo/client.(*QQClient).UploadGroupImage
>         github.com/Mrs4s/MiraiGo@v0.0.0-20210906051204-59288fc4dcf2/client/image.go:60
> github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.preProcessGroupSendingMessage
>         github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/api_handler.go:98
> github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.HandleSendGroupMsg
>         github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/api_handler.go:173
> github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.handleApiFrame
>         github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/remote.go:181
> github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.OnWsRecvMessage.func1
>         github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/remote.go:143
> github.com/ProtobufBot/Go-Mirai-Client/pkg/safe_ws.NewSafeWebSocket.func2.1
>         github.com/ProtobufBot/Go-Mirai-Client/pkg/safe_ws/safe_ws.go:78
> github.com/ProtobufBot/Go-Mirai-Client/pkg/util.SafeGo.func1
>         github.com/ProtobufBot/Go-Mirai-Client/pkg/util/util.go:118
> runtime.goexit
>         runtime/asm_amd64.s:1581
> upload failed
> github.com/Mrs4s/MiraiGo/client.(*QQClient).UploadGroupImage
>         github.com/Mrs4s/MiraiGo@v0.0.0-20210906051204-59288fc4dcf2/client/image.go:63
> github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.preProcessGroupSendingMessage
>         github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/api_handler.go:98
> github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.HandleSendGroupMsg
>         github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/api_handler.go:173
> github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.handleApiFrame
>         github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/remote.go:181
> github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.OnWsRecvMessage.func1
>         github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/remote.go:143
> github.com/ProtobufBot/Go-Mirai-Client/pkg/safe_ws.NewSafeWebSocket.func2.1
>         github.com/ProtobufBot/Go-Mirai-Client/pkg/safe_ws/safe_ws.go:78
> github.com/ProtobufBot/Go-Mirai-Client/pkg/util.SafeGo.func1
>         github.com/ProtobufBot/Go-Mirai-Client/pkg/util/util.go:118
> runtime.goexit
>         runtime/asm_amd64.s:1581
> ```
> 
> 私聊没问题，只会 failed to upload group image

可以考虑试试放行服务器上行的14000端口
