### ISSUE TITLE
群聊和私聊都遇到图片发送失败问题

### ISSUE THREAD

**Issue by ttlvip** [ProtobufBot/Go-Mirai-Client#14]
腾讯云Linux， 出口带宽1M， 链接的图片大小为406kb

`[36mINFO[0m[2021-10-01 17:39:52] Bot(1649565448) Private(649565448) <- <image url="http://域名/meituxiuxiu_7029.jpg"/> 
[31mERRO[0m[2021-10-01 17:40:12] failed to upload private image, dial tcp 180.102.111.81:14000: i/o timeout
connect error
github.com/Mrs4s/MiraiGo/client.(*QQClient).highwayUploadByBDH
	github.com/Mrs4s/MiraiGo@v0.0.0-20210906051204-59288fc4dcf2/client/highway.go:121
github.com/Mrs4s/MiraiGo/client.(*QQClient).UploadGroupImage
	github.com/Mrs4s/MiraiGo@v0.0.0-20210906051204-59288fc4dcf2/client/image.go:60
github.com/Mrs4s/MiraiGo/client.(*QQClient).uploadPrivateImage
	github.com/Mrs4s/MiraiGo@v0.0.0-20210906051204-59288fc4dcf2/client/image.go:135
github.com/Mrs4s/MiraiGo/client.(*QQClient).UploadPrivateImage
	github.com/Mrs4s/MiraiGo@v0.0.0-20210906051204-59288fc4dcf2/client/image.go:124
github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.preProcessPrivateSendingMessage
	github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/api_handler.go:51
github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.HandleSendPrivateMsg
	github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/api_handler.go:157
github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.handleApiFrame
	github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/remote.go:176
github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.OnWsRecvMessage.func1
	github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/remote.go:143
github.com/ProtobufBot/Go-Mirai-Client/pkg/safe_ws.NewSafeWebSocket.func2.1
	github.com/ProtobufBot/Go-Mirai-Client/pkg/safe_ws/safe_ws.go:78
github.com/ProtobufBot/Go-Mirai-Client/pkg/util.SafeGo.func1
	github.com/ProtobufBot/Go-Mirai-Client/pkg/util/util.go:118
runtime.goexit
	runtime/asm_amd64.s:1581
upload failed
github.com/Mrs4s/MiraiGo/client.(*QQClient).UploadGroupImage
	github.com/Mrs4s/MiraiGo@v0.0.0-20210906051204-59288fc4dcf2/client/image.go:63
github.com/Mrs4s/MiraiGo/client.(*QQClient).uploadPrivateImage
	github.com/Mrs4s/MiraiGo@v0.0.0-20210906051204-59288fc4dcf2/client/image.go:135
github.com/Mrs4s/MiraiGo/client.(*QQClient).UploadPrivateImage
	github.com/Mrs4s/MiraiGo@v0.0.0-20210906051204-59288fc4dcf2/client/image.go:124
github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.preProcessPrivateSendingMessage
	github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/api_handler.go:51
github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.HandleSendPrivateMsg
	github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/api_handler.go:157
github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.handleApiFrame
	github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/remote.go:176
github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.OnWsRecvMessage.func1
	github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/remote.go:143
github.com/ProtobufBot/Go-Mirai-Client/pkg/safe_ws.NewSafeWebSocket.func2.1
	github.com/ProtobufBot/Go-Mirai-Client/pkg/safe_ws/safe_ws.go:78
github.com/ProtobufBot/Go-Mirai-Client/pkg/util.SafeGo.func1
	github.com/ProtobufBot/Go-Mirai-Client/pkg/util/util.go:118
runtime.goexit
	runtime/asm_amd64.s:1581 `

**Comment by lz1998** [comment]
> 腾讯云Linux， 出口带宽1M， 链接的图片大小为406kb
> 
> `�[36mINFO�[0m[2021-10-01 17:39:52] Bot(1649565448) Private(649565448) <- <image url="http://域名/meituxiuxiu_7029.jpg"/> �[31mERRO�[0m[2021-10-01 17:40:12] failed to upload private image, dial tcp 180.102.111.81:14000: i/o timeout connect error github.com/Mrs4s/MiraiGo/client.(*QQClient).highwayUploadByBDH github.com/Mrs4s/MiraiGo@v0.0.0-20210906051204-59288fc4dcf2/client/highway.go:121 github.com/Mrs4s/MiraiGo/client.(*QQClient).UploadGroupImage github.com/Mrs4s/MiraiGo@v0.0.0-20210906051204-59288fc4dcf2/client/image.go:60 github.com/Mrs4s/MiraiGo/client.(*QQClient).uploadPrivateImage github.com/Mrs4s/MiraiGo@v0.0.0-20210906051204-59288fc4dcf2/client/image.go:135 github.com/Mrs4s/MiraiGo/client.(*QQClient).UploadPrivateImage github.com/Mrs4s/MiraiGo@v0.0.0-20210906051204-59288fc4dcf2/client/image.go:124 github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.preProcessPrivateSendingMessage github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/api_handler.go:51 github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.HandleSendPrivateMsg github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/api_handler.go:157 github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.handleApiFrame github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/remote.go:176 github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.OnWsRecvMessage.func1 github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/remote.go:143 github.com/ProtobufBot/Go-Mirai-Client/pkg/safe_ws.NewSafeWebSocket.func2.1 github.com/ProtobufBot/Go-Mirai-Client/pkg/safe_ws/safe_ws.go:78 github.com/ProtobufBot/Go-Mirai-Client/pkg/util.SafeGo.func1 github.com/ProtobufBot/Go-Mirai-Client/pkg/util/util.go:118 runtime.goexit runtime/asm_amd64.s:1581 upload failed github.com/Mrs4s/MiraiGo/client.(*QQClient).UploadGroupImage github.com/Mrs4s/MiraiGo@v0.0.0-20210906051204-59288fc4dcf2/client/image.go:63 github.com/Mrs4s/MiraiGo/client.(*QQClient).uploadPrivateImage github.com/Mrs4s/MiraiGo@v0.0.0-20210906051204-59288fc4dcf2/client/image.go:135 github.com/Mrs4s/MiraiGo/client.(*QQClient).UploadPrivateImage github.com/Mrs4s/MiraiGo@v0.0.0-20210906051204-59288fc4dcf2/client/image.go:124 github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.preProcessPrivateSendingMessage github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/api_handler.go:51 github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.HandleSendPrivateMsg github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/api_handler.go:157 github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.handleApiFrame github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/remote.go:176 github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.OnWsRecvMessage.func1 github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/remote.go:143 github.com/ProtobufBot/Go-Mirai-Client/pkg/safe_ws.NewSafeWebSocket.func2.1 github.com/ProtobufBot/Go-Mirai-Client/pkg/safe_ws/safe_ws.go:78 github.com/ProtobufBot/Go-Mirai-Client/pkg/util.SafeGo.func1 github.com/ProtobufBot/Go-Mirai-Client/pkg/util/util.go:118 runtime.goexit runtime/asm_amd64.s:1581 `

更新到最新版试试看，有一个旧版本私聊图片有问题

**Comment by ttlvip** [comment]
> > 腾讯云Linux， 出口带宽1M， 链接的图片大小为406kb
> > `�[36mINFO�[0m[2021-10-01 17:39:52] Bot(1649565448) Private(649565448) <- <image url="http://域名/meituxiuxiu_7029.jpg"/> �[31mERRO�[0m[2021-10-01 17:40:12] failed to upload private image, dial tcp 180.102.111.81:14000: i/o timeout connect error github.com/Mrs4s/MiraiGo/client.(*QQClient).highwayUploadByBDH github.com/Mrs4s/MiraiGo@v0.0.0-20210906051204-59288fc4dcf2/client/highway.go:121 github.com/Mrs4s/MiraiGo/client.(*QQClient).UploadGroupImage github.com/Mrs4s/MiraiGo@v0.0.0-20210906051204-59288fc4dcf2/client/image.go:60 github.com/Mrs4s/MiraiGo/client.(*QQClient).uploadPrivateImage github.com/Mrs4s/MiraiGo@v0.0.0-20210906051204-59288fc4dcf2/client/image.go:135 github.com/Mrs4s/MiraiGo/client.(*QQClient).UploadPrivateImage github.com/Mrs4s/MiraiGo@v0.0.0-20210906051204-59288fc4dcf2/client/image.go:124 github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.preProcessPrivateSendingMessage github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/api_handler.go:51 github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.HandleSendPrivateMsg github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/api_handler.go:157 github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.handleApiFrame github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/remote.go:176 github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.OnWsRecvMessage.func1 github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/remote.go:143 github.com/ProtobufBot/Go-Mirai-Client/pkg/safe_ws.NewSafeWebSocket.func2.1 github.com/ProtobufBot/Go-Mirai-Client/pkg/safe_ws/safe_ws.go:78 github.com/ProtobufBot/Go-Mirai-Client/pkg/util.SafeGo.func1 github.com/ProtobufBot/Go-Mirai-Client/pkg/util/util.go:118 runtime.goexit runtime/asm_amd64.s:1581 upload failed github.com/Mrs4s/MiraiGo/client.(*QQClient).UploadGroupImage github.com/Mrs4s/MiraiGo@v0.0.0-20210906051204-59288fc4dcf2/client/image.go:63 github.com/Mrs4s/MiraiGo/client.(*QQClient).uploadPrivateImage github.com/Mrs4s/MiraiGo@v0.0.0-20210906051204-59288fc4dcf2/client/image.go:135 github.com/Mrs4s/MiraiGo/client.(*QQClient).UploadPrivateImage github.com/Mrs4s/MiraiGo@v0.0.0-20210906051204-59288fc4dcf2/client/image.go:124 github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.preProcessPrivateSendingMessage github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/api_handler.go:51 github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.HandleSendPrivateMsg github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/api_handler.go:157 github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.handleApiFrame github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/remote.go:176 github.com/ProtobufBot/Go-Mirai-Client/pkg/bot.OnWsRecvMessage.func1 github.com/ProtobufBot/Go-Mirai-Client/pkg/bot/remote.go:143 github.com/ProtobufBot/Go-Mirai-Client/pkg/safe_ws.NewSafeWebSocket.func2.1 github.com/ProtobufBot/Go-Mirai-Client/pkg/safe_ws/safe_ws.go:78 github.com/ProtobufBot/Go-Mirai-Client/pkg/util.SafeGo.func1 github.com/ProtobufBot/Go-Mirai-Client/pkg/util/util.go:118 runtime.goexit runtime/asm_amd64.s:1581 `
> 
> 更新到最新版试试看，有一个旧版本私聊图片有问题

在腾讯云安全组放行14000端口后, 问题得到解决.
