### ISSUE TITLE
增加反向ws连接token验证与自动登录

### ISSUE THREAD

**Issue by yimo0908** [ProtobufBot/Go-Mirai-Client#2]
用反向ws连接云bot上游，因为过不了access_token验证，一直握手失败
```
time="2020-12-09 00:45:17" level=warning msg="连接Websocket服务器 ws://xn--v9x.net/ 时出现错误: websocket: bad handshake"
```
以及，似乎没有看到自动登录的设置。（如果是我眼拙，麻烦告知一下）

**Comment by lz1998** [comment]
需要使用pbbot-spring-boot-starter连接，建议参考[Spring-Mirai-Server](https://github.com/protobufbot/spring-mirai-server)。

自动登陆需要自己编写shell脚本/bat批处理启动，会从环境变量读取UIN、PASSWORD、PORT

```shell

export UIN=机器人QQ号
export PASSWORD=机器人密码
export PORT=9000（处理验证码用的界面端口）
./Go-Mirai-Client # 可以开在nohup或者screen

export UIN=另一个机器人QQ号
export PASSWORD=另一个机器人密码
export PORT=9001（处理验证码用的界面端口）
./Go-Mirai-Client # 可以开在nohup或者screen
```
如果是Windows，把export改成set

可以在QQ群335783090交流
