### ISSUE TITLE
机器人入群授予管理权限却无管理权限

### ISSUE THREAD

**Issue by 2mf8** [ProtobufBot/Go-Mirai-Client#3]
邀请机器人进群后，授予机器人管理权限，在调用机器人管理指令时发现机器人没有管理权限

**Comment by 2mf8** [comment]
![Uploading B10443B1-653E-4DBA-B600-A3F3683A2785.jpeg…]()

**Comment by lz1998** [comment]
可能是bug，等待 [miraigo](https://github.com/mrs4s/miraigo) 修复
