### ISSUE TITLE
多websocket连接

### ISSUE THREAD

**Issue by bystart** [ProtobufBot/Go-Mirai-Client#4]
希望能增加 被动连接websocket 且支持多个消息处理服务器进行连接

**Comment by lz1998** [comment]
被动 WS 暂时不考虑。 多个消息处理器已支持。使用 0.1.1 的 ServerGroups。

- 一个 ServerGroup 可以是一个/一组功能，可以有多个 ServerGroup 代表多个/多组功能。
- 每个 ServerGroup 可以包含多个 WS server(WS URL)，会在每个 ServerGroup 随机选择一个进行连接。
- 每个 WS Server 可以采用不同的编程语言进行开发。
- 每个 ServerGroup 可以配置独立的 EventFilter(事件过滤器)、RegexFilter(正则过滤器)、RegexReplace(正则替换)。

以上 `WebSocket` 简称`WS`

![image](https://user-images.githubusercontent.com/9082086/107243492-03edef00-6a68-11eb-8740-c876412fb672.png)
