### ISSUE TITLE
希望在未来版本编译linux armv7的包

### ISSUE THREAD

**Issue by f1owkang** [ProtobufBot/Go-Mirai-Client#5]
手里还有一台玩客云 架构是armv7 感谢

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by lz1998** [comment]
未来可以考虑使用 GitHub Actions 实现自动发布 releases，需要调研相关技术。

临时解决方案：在QQ群文件下载(335783090)
