### ISSUE TITLE
管理网页404错误

### ISSUE THREAD

**Issue by mengniu8** [ProtobufBot/Go-Mirai-Client#6]
我是在VPS上挂您的程序，运行后，打开http://服务器IP:9000 显示404错误。请问是我姿势不对吗？

**Comment by lz1998** [comment]
> 我是在VPS上挂您的程序，运行后，打开[http://服务器IP:9000](http://%E6%9C%8D%E5%8A%A1%E5%99%A8IP:9000) 显示404错误。请问是我姿势不对吗？

你是不是没把static文件夹放上去？

另外，如果在本地已经挂过了，可以把device文件复制到服务器上，会认为是同一个设备，编写启动脚本自动登陆更方便。

### Windows

```shell
set UIN=机器人QQ号
set PASSWORD=机器人QQ密码
set PORT=0
Go-Mirai-Client.exe
```

### Linux
```shell
chmod +x ./Go-Mirai-Client

export UIN=机器人QQ号
export PASSWORD=机器人QQ密码
export PORT=0
./Go-Mirai-Client
```

**Comment by mengniu8** [comment]
好的，万分感谢。我确实是忘记传static文件夹了。羞愧啊。

**Comment by lz1998** [comment]
> 好的，万分感谢。我确实是忘记传static文件夹了。羞愧啊。

已更新为单文件（全都打包在里面了）

最新版：https://github.com/ProtobufBot/Go-Mirai-Client/releases
