### ISSUE TITLE
接受到规定指令后断开连接，并无法发送消息

### ISSUE THREAD

**Issue by raindown200709** [ProtobufBot/Go-Mirai-Client#8]
<img src = 'https://ftp.bmp.ovh/imgs/2021/03/35b19f93dbd76f52.png' />

**Comment by lz1998** [comment]
用的哪个框架？

https://github.com/protobufbot/protobufbot

**Comment by raindown200709** [comment]
Spring-CQ

**Comment by lz1998** [comment]
> Spring-CQ

用新框架Spring-Mirai-Server，在上一条回复的链接里

**Comment by raindown200709** [comment]
已解决

**Comment by raindown200709** [comment]
上手不是很好，求做个视频

**Comment by lz1998** [comment]
> 上手不是很好，求做个视频

和spring cq使用方法基本一样，暂时没时间做视频
